### PR TITLE
Rewrote the whole damn thing aaghghhghg

### PR DESCRIPTION
**Pull request by philsturgeon**
Now that the divergence issues are somewhat solved, and the ideal workflow kinda exists, we dont have to point out things then awkwardly mumble about caveats later. 

This new approach to the talk loudly proclaims about using both OpenAPI and JSON Schema, points out which is good at what, identifies the caveats, and provides solutions to using both happily. 

If you wanna see this talk when its done, shove your GDPR-appproved PII into this form: http://bit.ly/2GXrEas

### CODE REVIEW

**Comment by philsturgeon** [comment]
Crap I still forgot to cover contract testing.

**Comment by philsturgeon** [comment]
Added contract testing :D

**Review by hskrasek — APPROVED** [review]
Not sure if you're looking for approves on this PR, but things look good to me. Didn't notice any glaring grammar or spelling mistakes either

**Comment by philsturgeon** [comment]
Thanks @hskrasek! Cant believe there are no glaring typos thats the first time ever.

**Pull request merged**
